baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Carlos Aguilera Ventura'
theme = "personal"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 2
  [[menu.main]]
    name = "Now"
    url = "/now/"
    weight = 3
